import type { CommitteeDetails } from './catalogApi';

type Props = { value: CommitteeDetails; onChange: (next: CommitteeDetails) => void };
type AgreementKey = 'previous_agreements' | 'new_agreements';

export function CommitteeEditor({ value, onChange }: Props) {
  const set = (patch: Partial<CommitteeDetails>) => onChange({ ...value, ...patch });
  const agreementRows = (key: AgreementKey, title: string) => <section className="committee-edit-section">
    <h3>{title}</h3>
    {value[key].map((row, index) => <div className="committee-edit-row" key={index}>
      <label>Compromiso<input value={row.title} onChange={(event) => set({ [key]: value[key].map((item, i) => i === index ? { ...item, title: event.target.value } : item) })} /></label>
      <label>Responsable<input value={row.owner} onChange={(event) => set({ [key]: value[key].map((item, i) => i === index ? { ...item, owner: event.target.value } : item) })} /></label>
      <label>Fecha límite<input type="date" value={row.due_date} onChange={(event) => set({ [key]: value[key].map((item, i) => i === index ? { ...item, due_date: event.target.value } : item) })} /></label>
      <label>Estado<select value={row.status} onChange={(event) => set({ [key]: value[key].map((item, i) => i === index ? { ...item, status: event.target.value as typeof row.status } : item) })}><option value="new">Nuevo</option><option value="pending">Pendiente</option><option value="in_progress">En proceso</option><option value="done">Cumplido</option></select></label>
      <button type="button" onClick={() => set({ [key]: value[key].filter((_, i) => i !== index) })}>Quitar</button>
    </div>)}
    <button type="button" onClick={() => set({ [key]: [...value[key], { title: '', owner: '', due_date: '', status: key === 'new_agreements' ? 'new' : 'pending' }] })}>+ Agregar compromiso</button>
  </section>;

  return <div className="committee-editor">
    <h3>Seguimiento del comité</h3>
    <div className="catalog-form-grid"><label>Fecha y hora de reunión<input type="datetime-local" value={value.meeting_at?.slice(0, 16) ?? ''} onChange={(event) => set({ meeting_at: event.target.value || null })} /></label><label>Lugar<input value={value.location} onChange={(event) => set({ location: event.target.value })} /></label><label>Audiencia<input value={value.audience} onChange={(event) => set({ audience: event.target.value })} placeholder="Comité directivo, donantes…" /></label></div>
    <section className="committee-edit-section"><h3>Actividades y cronograma</h3>{value.activities.map((row, index) => <div className="committee-edit-row" key={index}><label>Actividad<input value={row.title} onChange={(event) => set({ activities: value.activities.map((item, i) => i === index ? { ...item, title: event.target.value } : item) })} /></label><label>Avance %<input type="number" min="0" max="100" value={row.progress} onChange={(event) => set({ activities: value.activities.map((item, i) => i === index ? { ...item, progress: Number(event.target.value) } : item) })} /></label><button type="button" onClick={() => set({ activities: value.activities.filter((_, i) => i !== index) })}>Quitar</button></div>)}<button type="button" onClick={() => set({ activities: [...value.activities, { title: '', progress: 0 }] })}>+ Agregar actividad</button></section>
    <section className="committee-edit-section"><h3>Alertas y riesgos</h3>{value.alerts.map((row, index) => <div className="committee-edit-row" key={index}><label>Alerta<input value={row.title} onChange={(event) => set({ alerts: value.alerts.map((item, i) => i === index ? { ...item, title: event.target.value } : item) })} /></label><label>Descripción<textarea value={row.description} onChange={(event) => set({ alerts: value.alerts.map((item, i) => i === index ? { ...item, description: event.target.value } : item) })} /></label><label>Prioridad<select value={row.priority} onChange={(event) => set({ alerts: value.alerts.map((item, i) => i === index ? { ...item, priority: event.target.value as typeof row.priority } : item) })}><option value="high">Alta</option><option value="medium">Media</option><option value="low">Baja</option></select></label><label>Responsable<input value={row.owner} onChange={(event) => set({ alerts: value.alerts.map((item, i) => i === index ? { ...item, owner: event.target.value } : item) })} /></label><label>Acción siguiente<input value={row.next_action} onChange={(event) => set({ alerts: value.alerts.map((item, i) => i === index ? { ...item, next_action: event.target.value } : item) })} /></label><button type="button" onClick={() => set({ alerts: value.alerts.filter((_, i) => i !== index) })}>Quitar</button></div>)}<button type="button" onClick={() => set({ alerts: [...value.alerts, { title: '', description: '', priority: 'medium', owner: '', next_action: '' }] })}>+ Agregar alerta</button></section>
    <section className="committee-edit-section"><h3>Presupuesto</h3>{value.budget.map((row, index) => <div className="committee-edit-row" key={index}><label>Componente<input value={row.component} onChange={(event) => set({ budget: value.budget.map((item, i) => i === index ? { ...item, component: event.target.value } : item) })} /></label><label>Presupuesto<input type="number" min="0" value={row.planned} onChange={(event) => set({ budget: value.budget.map((item, i) => i === index ? { ...item, planned: Number(event.target.value) } : item) })} /></label><label>Ejecutado<input type="number" min="0" value={row.spent} onChange={(event) => set({ budget: value.budget.map((item, i) => i === index ? { ...item, spent: Number(event.target.value) } : item) })} /></label><button type="button" onClick={() => set({ budget: value.budget.filter((_, i) => i !== index) })}>Quitar</button></div>)}<button type="button" onClick={() => set({ budget: [...value.budget, { component: '', planned: 0, spent: 0 }] })}>+ Agregar componente</button></section>
    {agreementRows('previous_agreements', 'Acuerdos anteriores')}
    {agreementRows('new_agreements', 'Nuevos compromisos')}
  </div>;
}
