import type { BuilderPaletteItem } from './types';

export const FIELD_CATALOG: BuilderPaletteItem[] = [
  { category: 'Texto', type: 'TEXT', label: 'Texto corto', description: 'Nombres, identificaciones y codigos' },
  { category: 'Texto', type: 'DOCUMENT_ID', label: 'Documento / ID', description: 'Cedula, pasaporte, NIT o codigo alfanumerico' },
  { category: 'Texto', type: 'TEXTAREA', label: 'Texto largo', description: 'Observaciones y descripciones' },
  { category: 'Texto', type: 'EMAIL', label: 'Correo electronico', description: 'Email con validacion de formato' },
  { category: 'Texto', type: 'PHONE', label: 'Telefono', description: 'Numero de contacto' },
  { category: 'Texto', type: 'URL', label: 'URL', description: 'Enlace web validado' },
  { category: 'Numericos', type: 'NUMBER', label: 'Numero', description: 'Valor numerico general' },
  { category: 'Numericos', type: 'INTEGER', label: 'Numero entero', description: 'Conteos exactos y edades' },
  { category: 'Numericos', type: 'DECIMAL', label: 'Numero decimal', description: 'Pesos, areas y porcentajes' },
  { category: 'Numericos', type: 'PERCENTAGE', label: 'Porcentaje', description: 'Valor entre 0 y 100' },
  { category: 'Numericos', type: 'CURRENCY', label: 'Moneda', description: 'Valor monetario' },
  { category: 'Opciones', type: 'BOOLEAN', label: 'Si / No', description: 'Respuesta booleana' },
  { category: 'Opciones', type: 'SELECT', label: 'Seleccion unica', description: 'Una opcion de una lista' },
  { category: 'Opciones', type: 'MULTISELECT', label: 'Seleccion multiple', description: 'Varias opciones de una lista' },
  { category: 'Opciones', type: 'DROPDOWN', label: 'Menu desplegable', description: 'Seleccion en listas extensas' },
  { category: 'Fecha y hora', type: 'DATE', label: 'Fecha', description: 'Selector de fecha' },
  { category: 'Fecha y hora', type: 'TIME', label: 'Hora', description: 'Selector de hora' },
  { category: 'Fecha y hora', type: 'DATETIME', label: 'Fecha y hora', description: 'Marca temporal combinada' },
  { category: 'Fecha y hora', type: 'YEAR', label: 'Año', description: 'Periodo anual' },
  { category: 'Fecha y hora', type: 'MONTH', label: 'Mes', description: 'Periodo mensual' },
  { category: 'Fecha y hora', type: 'WEEK', label: 'Semana', description: 'Periodo semanal' },
  { category: 'Multimedia', type: 'IMAGE', label: 'Fotografia', description: 'Evidencia fotografica' },
  { category: 'Multimedia', type: 'AUDIO', label: 'Audio', description: 'Grabacion de voz' },
  { category: 'Multimedia', type: 'VIDEO', label: 'Video', description: 'Registro audiovisual' },
  { category: 'Multimedia', type: 'FILE', label: 'Archivo', description: 'Documento adjunto' },
  { category: 'Multimedia', type: 'PDF', label: 'PDF', description: 'Soporte documental PDF' },
  { category: 'Multimedia', type: 'MULTIFILE', label: 'Multiples archivos', description: 'Conjunto de evidencias adjuntas' },
  { category: 'Multimedia', type: 'SIGNATURE', label: 'Firma digital', description: 'Firma en pantalla tactil' },
  { category: 'GIS', type: 'GPS', label: 'Punto GPS', description: 'Coordenada geografica' },
  { category: 'GIS', type: 'GEOTRACE', label: 'Linea o ruta', description: 'Trayecto de multiples puntos' },
  { category: 'GIS', type: 'GEOSHAPE', label: 'Poligono o area', description: 'Delimitacion geografica' },
  { category: 'Estructuras', type: 'REPEAT', label: 'Tabla repetida', description: 'Subformulario dinamico' },
  { category: 'Estructuras', type: 'MATRIX', label: 'Matriz', description: 'Escala o cuadricula estatica' },
  { category: 'Estructuras', type: 'PARENT_CHILD', label: 'Padre - hijo', description: 'Seguimiento relacional longitudinal' },
  { category: 'Logica', type: 'CALCULATE', label: 'Calculo', description: 'Resultado automatico' },
  { category: 'Logica', type: 'REFERENCE', label: 'Referencia externa', description: 'Dato vinculado a otra base' },
  { category: 'Logica', type: 'LOOKUP', label: 'Lookup', description: 'Precarga desde otra fuente' },
  { category: 'Logica', type: 'HIDDEN', label: 'Variable oculta', description: 'Dato interno no visible' },
  { category: 'Captura', type: 'BARCODE', label: 'Codigo de barras', description: 'Escaneo de etiquetas' },
  { category: 'Captura', type: 'QR', label: 'Codigo QR', description: 'Escaneo de codigos QR' },
  { category: 'Captura', type: 'OCR', label: 'OCR', description: 'Lectura de texto desde imagen o documento' },
  { category: 'Experiencia', type: 'NPS', label: 'NPS', description: 'Puntuacion de 0 a 10' },
  { category: 'Experiencia', type: 'LIKERT_5', label: 'Likert 5 puntos', description: 'Escala de percepcion de 1 a 5' },
  { category: 'Experiencia', type: 'LIKERT_7', label: 'Likert 7 puntos', description: 'Escala de percepcion de 1 a 7' },
  { category: 'Experiencia', type: 'RATING', label: 'Calificacion', description: 'Estrellas o escala visual' },
  { category: 'Experiencia', type: 'RANKING', label: 'Ranking', description: 'Ordenamiento de prioridades' },
  { category: 'Sistema', type: 'UUID', label: 'UUID', description: 'Identificador unico global' },
  { category: 'Sistema', type: 'RESPONSE_ID', label: 'ID de respuesta', description: 'Identificador del registro' },
  { category: 'Auditoria', type: 'INTERVIEW_DURATION', label: 'Tiempo de entrevista', description: 'Duracion de la captura' },
  { category: 'Auditoria', type: 'CAPTURED_BY', label: 'Usuario capturador', description: 'Responsable del registro' },
  { category: 'Auditoria', type: 'CHANGE_HISTORY', label: 'Historial de cambios', description: 'Trazabilidad de versiones' },
];
